export const trackListForSkeleton = [
  {
    id: '1',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Guilt',
    moreInfo: '',
    author: 'Nero',
    album: 'Welcome Reality',
    time: '4:44',
  },
  {
    id: '2',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Elektro',
    moreInfo: '',
    author: 'Dynoro, Outwork, Mr. Gee',
    album: 'Elektro',
    time: '2:22',
  },
  {
    id: '3',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'I’m Fire',
    moreInfo: '',
    author: 'Ali Bakgor',
    album: 'I’m Fire',
    time: '2:22',
  },
  {
    id: '4',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Non Stop',
    moreInfo: '(Remix)',
    author: 'Стоункат, Psychopath',
    album: 'Non Stop',
    time: '4:12',
  },
  {
    id: '5',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Run Run',
    moreInfo: '(feat. AR/CO)',
    author: 'Jaded, Will Clarke, AR/CO',
    album: 'Run Run',
    time: '2:54',
  },
  {
    id: '6',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Eyes on Fire',
    moreInfo: '(Zeds Dead Remix)',
    author: 'Blue Foundation, Zeds Dead ',
    album: 'Eyes on Fire',
    time: '5:20',
  },
  {
    id: '7',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Mucho Bien',
    moreInfo: '(Hi Profile Remix)',
    author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
    album: 'Mucho Bien',
    time: '3:41',
  },
  {
    id: '8',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Knives n Cherries',
    moreInfo: '',
    author: 'minthaze',
    album: 'Captivating',
    time: '1:48',
  },
  {
    id: '9',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'How Deep Is Your Love',
    moreInfo: '',
    author: 'Calvin Harris, Disciples',
    album: 'How Deep Is Your Love',
    time: '3:32',
  },
  {
    id: '10',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Morena',
    moreInfo: '',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    time: '3:36',
  },
  {
    id: '11',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Morena',
    moreInfo: '',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    time: '3:36',
  },
  {
    id: '12',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Morena',
    moreInfo: '',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    time: '3:36',
  },
  {
    id: '13',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Guilt',
    moreInfo: '',
    author: 'Nero',
    album: 'Welcome Reality',
    time: '4:44',
  },
  {
    id: '14',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Elektro',
    moreInfo: '',
    author: 'Dynoro, Outwork, Mr. Gee',
    album: 'Elektro',
    time: '2:22',
  },
  {
    id: '15',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'I’m Fire',
    moreInfo: '',
    author: 'Ali Bakgor',
    album: 'I’m Fire',
    time: '2:22',
  },
  {
    id: '16',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Non Stop',
    moreInfo: '(Remix)',
    author: 'Стоункат, Psychopath',
    album: 'Non Stop',
    time: '4:12',
  },
  {
    id: '17',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Run Run',
    moreInfo: '(feat. AR/CO)',
    author: 'Jaded, Will Clarke, AR/CO',
    album: 'Run Run',
    time: '2:54',
  },
  {
    id: '18',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Eyes on Fire',
    moreInfo: '(Zeds Dead Remix)',
    author: 'Blue Foundation, Zeds Dead ',
    album: 'Eyes on Fire',
    time: '5:20',
  },
  {
    id: '19',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Mucho Bien',
    moreInfo: '(Hi Profile Remix)',
    author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
    album: 'Mucho Bien',
    time: '3:41',
  },
  {
    id: '20',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Knives n Cherries',
    moreInfo: '',
    author: 'minthaze',
    album: 'Captivating',
    time: '1:48',
  },
  {
    id: '21',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'How Deep Is Your Love',
    moreInfo: '',
    author: 'Calvin Harris, Disciples',
    album: 'How Deep Is Your Love',
    time: '3:32',
  },
  {
    id: '22',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Morena',
    moreInfo: '',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    time: '3:36',
  },
  {
    id: '23',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Morena',
    moreInfo: '',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    time: '3:36',
  },
  {
    id: '24',
    image: 'img/icon/sprite.svg#icon-note',
    name: 'Morena',
    moreInfo: '',
    author: 'Tom Boxer',
    album: 'Soundz Made in Romania',
    time: '3:36',
  },
]
